### ISSUE TITLE
sheets: appending a new row breaks above "Array result was not expanded because it would overwrite data"

### ISSUE THREAD

**Issue by sneko** [googleapis/google-api-go-client#1041]
Hi,

I have a document that gets a new row each time a webhook is triggered.

My column B should be generated based on another tab. The formula in B2 is something like:
```
=ARRAYFORMULA(IFNA(VLOOKUP($K2:$K, other_tab!$A:$C, 3, false),""))
```

Anyway, it works well when adding row on my own through the UI, but when it's from a Golang script by injecting this line:
```
	values := [][]interface{}{
		[]interface{}{
			variable1, nil, variable2, variable3, ...
		},
	}
```

I get this error:
```
Array result was not expanded because it would overwrite data in B608.
```

What's weird is if I go to B608 and just press backspace the error will disappear. I thought "nil" would do the trick to let the default behavior to the cell. I also tried with an empty cell:
```
	values := [][]interface{}{
		[]interface{}{
			variable1, "", variable2, variable3, ...
		},
	}
```

... but same error.

Do you know what could avoid breaking this? (since from the UI it works perfectly...)

Thank you 😄

**Comment by codyoss** [comment]
Hey, I am not too familiar with this API. This issue tracker is primary used for questions and features for the generated code. Since this question is related to the API I would suggest reaching out with one of the methods listed on the [Sheets Support page](https://developers.google.com/sheets/api/support). 

These docs may help for ValueRange:
> ... For input, supported value types are: bool, string, and double. Null values will be skipped. To set a cell to an empty value, set the string value to an empty string.

Sorry I could not be of more help.
