### ISSUE TITLE
docs: incorrect documentaion for compute ResourcePolicyDailyCycle struct

### ISSUE THREAD

**Issue by misterjacko** [googleapis/google-api-go-client#1177]
The description for the `daysInCycle` property of compute's `ResourcePolicyDailyCycle` struct is incorrect. It reads:

 "Defines a schedule with units measured in **months**. The value determines how many **months** pass between the start of each cycle."
 
 Daily cycle resource policy schedules are measured in days and further are restricted to 1 day. Anything over and you would use a weekly policy and anything under you would use hourly. 
 
 Documentation should be changed to reflect Days instead of Months and should outline that the only accepted value for this property is `1`.

**Comment by codyoss** [comment]
Hey @misterjacko thanks for the feedback on the compute api. As I mentioned in the PR you raised in order to fix this we would need to update the source that these APIs are generated from. I would recommend raising an issue one on of the compute issues trackers from [their support page](https://cloud.google.com/compute/docs/getting-support). Thanks you for finding this defect!
