### ISSUE TITLE
run: Fetching single service returns 404

### ISSUE THREAD

**Issue by alexzimmer96** [googleapis/google-api-go-client#1237]
It seems that working on a single Cloud Run Service is not possible. The example code fails with an error 404. Calling the API directly, at e.g. `https://europe-west1-run.googleapis.com/apis/serving.knative.dev/v1/namespaces/SOME-PROJECT-ID-OR-NAME/services/MY-SERVICE-NAME` works as expected.

This error also appears when trying to modify this object using the `svc.Namespaces.Services.ReplaceService` method.

#### Environment details

  - Programming language: Go
  - OS: Linux
  - Language runtime version: 1.17.1
  - Package version: v0.57.0

#### Steps to reproduce

```go
package main

import (
	"context"
	"fmt"
	"google.golang.org/api/run/v1"
	"log"
)

func main() {
	const project = "SOME-PROJECT-ID-OR-NAME"
	svc, _ := run.NewService(context.Background())

	list, _ := svc.Namespaces.Services.List(fmt.Sprintf("namespaces/%s", project)).Do()

	item := list.Items[0]
	log.Printf("found service with name: %s\n", item.Metadata.Name) // Expecting this beeing "MY-SERVICE-NAME"

	_, err := svc.Namespaces.Services.List(fmt.Sprintf("namespaces/%s/services/%s", project, item.Metadata.Name)).Do()
	if err != nil {
		log.Fatalf("could not query for service \"%s\": %s", item.Metadata.Name, err) // Error thrown here
	}
}
```

Error that is thrown:
```
could not query for service "MY-SERVICE-NAME": googleapi: Error 404: Requested entity was not found., notFound
```

Thanks in advance!

**Comment by codyoss** [comment]
Without trying this code out I assume the issue is with regional endpoints. Looking at the generated client it uses the non-regional endpoint by default which works for some requests but not all.

https://github.com/googleapis/google-api-go-client/blob/57b174424d11c0dd2bb736155bd756c1a52135ff/run/v1/run-gen.go#L77

As you said calling the API directly works, but there you are providing a regional endpoint. To do the same with this client you can pass an [option](https://pkg.go.dev/google.golang.org/api/option#WithEndpoint) to the service constructor: `option.WithEndpoint("https://europe-west1-run.googleapis.com/")`.  Let me know if that solves the issue!

**Comment by alexzimmer96** [comment]
Thanks, this did the trick.
I think this ticket can be closed.
