### ISSUE TITLE
chat: Invalid project number

### ISSUE THREAD

**Issue by martinscholz83** [googleapis/google-api-go-client#1328]
When trying to create a message with chat API like this

```go
ctx := context.Background()
opts := []option.ClientOption{
                option.WithScopes("https://www.googleapis.com/auth/chat.bot"),
		option.WithCredentialsFile("chatapi-333918-18288d25e907.json"),
	}
	service, err := chat.NewService(ctx, opts...)
	if err != nil {
		log.Fatal(err)
	}

	spaceService := chat.NewSpacesService(service)
	message := &chat.Message{Text: "Test"}
	call := spaceService.Messages.Create("spaces/XXXXXXXX", message)
	_, err = call.Do()
	if err != nil {
		log.Println(err.Error())
	}
```
I get `Error 404: Invalid project number., notFound`.

Something I missed here, because there is no place to set the project number.

**Comment by codyoss** [comment]
Hey, I am not an expert on this API, but perhaps there is some backend linking that needs to be done? I found this SO that seems somewhat relevant: https://stackoverflow.com/questions/63495912/send-message-to-google-chat-using-the-rest-api-google-example-not-working-in-20

It mentions configuring a project number. 

These clients are autogenerated from a public spec, a better place to ask a question like this would be on one of the links mentioned on the [Chat Support Page](https://developers.google.com/chat/support). Hope that helps!
