### ISSUE TITLE
idtoken: Can't use impersonated service account token

### ISSUE THREAD

**Issue by j0hnsmith** [googleapis/google-api-go-client#1393]
#### Environment details

  - Programming language: Go
  - OS: all
  - Language runtime version: all
  - Package version: v0.65.0

#### Steps to reproduce

  1. `authClient, err := idtoken.NewClient(ctx, endpoint)`

## Problem
Trying to use an `impersonated_service_account` token doesn't work because _only_ tokens with type `service_account` are supported.

https://github.com/googleapis/google-api-go-client/blob/c890ff5f4b6246b4f87de68bc2f1fe8f0b3c68f9/idtoken/idtoken.go#L139-L141

Anywhere a service account can be used an _impersonated service account_ should also be valid. I'm getting the error `idtoken: credential must be service_account, found "impersonated_service_account"`

**Comment by codyoss** [comment]
Are you trying to create an idtoken from an impersonated service account? If so I would recommend this method in the impersonate package: [IDTokenSource](https://pkg.go.dev/google.golang.org/api/impersonate#IDTokenSource).

**Comment by j0hnsmith** [comment]
No, I want an "HTTP Client that automatically adds an ID token to each request via an Authorization header". I know there are other token source implementations however `idtoken.NewClient()` explicitly does't support `option.WithTokenSource` (see below).

https://github.com/googleapis/google-api-go-client/blob/c890ff5f4b6246b4f87de68bc2f1fe8f0b3c68f9/idtoken/idtoken.go#L28-L48

The exact functionality I want is provided by `idtoken.NewClient()`... apart from `impersonated_service_account` tokens not being valid.

**Comment by j0hnsmith** [comment]
@codyoss Hi, I see you changed the label to `question`, I'm confused, at the least this is a feature request, no?

If you think that `idtoken.NewClient(ctx, endpoint)` shouldn't work with an impersonated service account can you give a reason why?

**Comment by bombsimon** [comment]
I have a similar problem but with `external_account` rather than `impersonated_service_account`.

I have a [Workload Identity Federation](https://cloud.google.com/iam/docs/workload-identity-federation) setup and am using [Keyless API authentication](https://cloud.google.com/blog/products/identity-security/enable-keyless-access-to-gcp-with-workload-identity-federation), basically just setting `GOOGLE_APPLICATION_CREDENTIALS` to the path of my JSON file without credentials. This works fine when using access tokens (`FindDefaultCredentials`) which you do for most SDK clients and services, however I also use [IAP](https://cloud.google.com/iap) which obviously requires an ID token.

My first question would be if this is even intended to be supported, that is to get an ID token for an `external_account`?

If so, would my issue be included in the scope for this issue or should I open a new one? Or is there in fact a way for me to actually get a token source that returns ID tokens since I also need to create a client that automatically sets a valid token on each request. I looked into `impersonate.IDTokenSource` but did not get that to work, is it expected to work with `external_account`?

**Comment by senthilkumarkj** [comment]
I hit the same problem described above. Is there a solution?

**Comment by codyoss** [comment]
This is now supported as of https://github.com/googleapis/google-api-go-client/pull/1792

**Comment by senthilkumarkj** [comment]
looks like the above PR added support only for type `impersonated_service_account` but not type `external_account ` used in workload identity https://google.aip.dev/auth/4117

**Comment by codyoss** [comment]
@senthilkumarkj That was intentional as the original issue was about `impersonated_service_account`. `external_account` should be a new different issue to be tracked.
