### ISSUE TITLE
NodePool Get/Describe returns the desired number of node

### ISSUE THREAD

**Issue by mintcckey** [googleapis/google-api-go-client#1917]
This question is regarding the container service (GKE).
I am trying to get the `desired number of nodes of a nodepool` (especially when the nodepool is managed by a CA, cluster autoscaler). However, I tried both the go SDK and the gcloud CLI. Neither returns the desired number. I wonder if there is a way to achieve it. Thanks!

**Comment by noahdietz** [comment]
Hello. To start I will point to the `gcloud` docs  for [Viewing node pools in a cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/node-pools#viewing_node_pools_in_a_cluster) just to make sure that this has been tried.

As far as the Go SDK, one can **set** the desired NodePool size via a [`SetNodePoolRequest`](https://pkg.go.dev/google.golang.org/api@v0.114.0/container/v1#SetNodePoolSizeRequest) with a [`SetSize`](https://pkg.go.dev/google.golang.org/api@v0.114.0/container/v1#ProjectsLocationsClustersNodePoolsService.SetSize) call. 
For **reading** that value, I believe it corresponds to the `InitialNodeCount` on a [`NodePool`](https://pkg.go.dev/google.golang.org/api@v0.114.0/container/v1#NodePool), but I'm not 100% sure. Assuming you have an [Autoscaling configuration](https://pkg.go.dev/google.golang.org/api@v0.114.0/container/v1#NodePoolAutoscaling), the actual number of nodes in the pool will likely change from this initial number.

Otherwise, I'd encourage you to search the [existing public issues](https://issuetracker.google.com/savedsearches/559746), and possibly [open your own](https://issuetracker.google.com/issues/new?component=187077&template=0) to determine the API element that correlates to the field information you are looking for and then find it in the Go SDK/gcloud surface.

Hope that helps.

**Comment by noahdietz** [comment]
I'm going to close this for now.

**Comment by mintcckey** [comment]
@noahdietz Thanks for providing more information. For others who might have similar questions, I found this [explanation](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/165#issuecomment-655052933) dated maybe 2-3 years back. I am not sure if it still holds but it could be used as some reference. 

However, I am still trying to figure out if the `InitialNodeCount` is only for a single zone when the autoscaling is enabled and the location policy is set to `BALANCED`. It seems so but I haven't found any documentation to confirm my assumption. Thanks.
