### ISSUE TITLE
Can you start tagging releases?

### ISSUE THREAD

**Issue by peterbourgon** [googleapis/google-api-go-client#198]
Releases tagged as semantic versions (e.g. `v0.1.2`) are the canonical way package managers in the Go ecosystem manage dependencies. Is it possible to start tagging stable releases in this repo? Thanks! :)

**Comment by jba** [comment]
@peterbourgon We intend to be well-behaved players in the dep ecosystem. This is a problematic repo because it contains a code generator,  support packages for the generated code, and over 100 generated API clients. I assume the decision to version at the repo level still stands and is not under serious review? (Because it certainly makes our lives harder.)

Under that assumption, we came up with the following plan:

* Any backwards-compatible change to any of the generated clients will cause a minor version bump. Expect a lot of these.
* Changing the support packages will result in a major, minor or patch bump, as per the semver spec.
* A commit that changes only the code generator will not result in a new semver tag. The code generator is not part of the exposed API of this repo.
* Sometimes we change the code generator in a way that produces backwards-incompatible code, usually for corner cases. When we regenerate clients after such a change, we will bump the major version, even if only one client is affected (see [Genesis 18:24-33](http://www.mechon-mamre.org/p/pt/pt0118.htm#24) for precedent).

/cc @zombiezen @broady @adams-sarah

**Comment by peterbourgon** [comment]
> I assume the decision to version at the repo level still stands and is not under serious review?

Yes, and not only for dep, but also for ~every other package manager, AFAIK.

**Comment by jefferai** [comment]
govendor and godep do not rely on tagged releases.

**Comment by peterbourgon** [comment]
@jefferai No tool _relies_ on tagged releases; all tools are able to work with specific revs.

**Comment by jba** [comment]
We're going to wait until vgo support lands in Go 1.11  before taking action on this.

**Comment by peterbourgon** [comment]
@jba There's no reason to wait that long.

**Comment by jadekler** [comment]
This will be addressed shortly when we begin Go module work. Closing this specific issue as the work will span multiple repositories.
