### ISSUE TITLE
Google Doc - How to parse doc and get text of selected item from dropdown

### ISSUE THREAD

**Issue by darrendao** [googleapis/google-api-go-client#2278]
In my google doc, I have a dropdown list. How do I parse the the doc to get the text of the selected item of that dropdown list? For normal text, I would parse for the content of the [TextRun](https://github.com/googleapis/google-api-go-client/blob/510f0f92034370f5164063af521c7a383b823b3e/docs/v1/docs-gen.go#L6567) ParagraphElement. However, that doesn't work when dealing with dropdown list. The content is not a text element.

**Comment by noahdietz** [comment]
Hi there! I'm not a Google Docs expert, but I took a look at this. I made a document with some dropdown items inline. I then queried the JSON API directly via the [API explorer](https://developers.google.com/docs/api/reference/rest/v1/documents/get) and inspected the response. Unfortunately, it looks like the REST API doesn't present dropdown items in any meaningful way. Looks like it is Checkout the screenshots below.

<img width="338" alt="Screenshot 2023-11-28 at 2 12 06 PM" src="https://github.com/googleapis/google-api-go-client/assets/6644735/72d5b0b6-71cb-43ba-ad78-4686739130bf">

<img width="491" alt="Screenshot 2023-11-28 at 2 14 32 PM" src="https://github.com/googleapis/google-api-go-client/assets/6644735/416235e3-3ad2-4e3d-a302-0ee1a2e4e873">

I didn't see any special styles or formatting references in the full response. As such, it doesn't seem possible to consume dropdown items via the REST API, I'm sorry. I would recommend providing this feedback via their [public issue tracker](https://developers.google.com/docs/api/support).

I'm going to close this issue because the client can only represent what is in the API.
