### ISSUE TITLE
option.WithCredentialsJSON incompatible with option.WithHTTPClient

### ISSUE THREAD

**Issue by jamesolasx** [googleapis/google-api-go-client#2497]
I am creating the compute client like this:

```	
parsedProxyURL, err := url.Parse("http://127.0.0.1:8080")

	httpClient := &http.Client{
		Transport: &http.Transport{
			Proxy:           http.ProxyURL(parsedProxyURL),
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
	}
	client, err := sheets.NewService(ctx, option.WithCredentialsJSON([]byte(credential)), option.WithHTTPClient(httpClient))
```

However, when I make try to instantiate an instance I get googleapi: Error 401: Login Required, required. Removing the option.WithHTTPClient and the issue is gone.

Error:
```

{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Login Required.",
        "domain": "global",
        "reason": "required",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.apps.sheets.v4.SpreadsheetsService.BatchUpdateSpreadsheet",
          "service": "sheets.googleapis.com"
        }
      }
    ]
  }
}
```

I noticed a same error.
https://github.com/googleapis/google-api-go-client/issues/404
There seems to be no specific solution given.

**Comment by quartzmo** [comment]
I'm not entirely sure what you are trying to do, but I think maybe you want to use the [`option.WithEndpoint`](https://pkg.go.dev/google.golang.org/api/option#WithEndpoint) option instead of replacing the default `http.Client`. Maybe the `TestTranslateText` example shown in https://github.com/googleapis/google-api-go-client/blob/main/testing.md#testing-http-services-using-fakes could help.

**Comment by quartzmo** [comment]
I updated the title of this issue, but it's just a guess. Please edit the title to precisely describe your question or problem.

**Comment by quartzmo** [comment]
Will this solution work for you? https://github.com/golang/oauth2/issues/182#issuecomment-211443477

**Comment by quartzmo** [comment]
See: [Compute Client: option.WithCredentialsFile incompatible with option.WithHTTPClient #404](https://github.com/googleapis/google-api-go-client/issues/404).

**Comment by jamesolasx** [comment]
> I'm not entirely sure what you are trying to do, but I think maybe you want to use the [`option.WithEndpoint`](https://pkg.go.dev/google.golang.org/api/option#WithEndpoint) option instead of replacing the default `http.Client`. Maybe the `TestTranslateText` example shown in https://github.com/googleapis/google-api-go-client/blob/main/testing.md#testing-http-services-using-fakes could help.

YES~
In some cases, I need to use http or socks proxy to create a client and operate google sheets through sheets api

**Comment by codyoss** [comment]
This issue is by design although our docs could be clearer here. From our docs [option.WithHTTPClient](https://pkg.go.dev/google.golang.org/api/option#WithHTTPClient):

WithHTTPClient returns a ClientOption that specifies the HTTP client to use as the basis of communications. This option may only be used with services that support HTTP as their communication transport. When used, the WithHTTPClient option takes precedent over all other supplied options.

If you override the HTTP client it is expected that your client take care of authorizing requests. You can use https://pkg.go.dev/google.golang.org/api/transport/http#NewTransport to help you create a transport that you can supply authorization.

@quartzmo I think we should treat this as a docs bug and we should say this more explicitly. I thought this was started somewhere, but it seems it is not, at least in the options package.

**Comment by jamesolasx** [comment]
> This issue is by design although our docs could be clearer here. From our docs [option.WithHTTPClient](https://pkg.go.dev/google.golang.org/api/option#WithHTTPClient):
> 
> WithHTTPClient returns a ClientOption that specifies the HTTP client to use as the basis of communications. This option may only be used with services that support HTTP as their communication transport. When used, the WithHTTPClient option takes precedent over all other supplied options.
> 
> If you override the HTTP client it is expected that your client take care of authorizing requests. You can use https://pkg.go.dev/google.golang.org/api/transport/http#NewTransport to help you create a transport that you can supply authorization.
> 
> @quartzmo I think we should treat this as a docs bug and we should say this more explicitly. I thought this was started somewhere, but it seems it is not, at least in the options package.

Would it be possible for you to provide me with a sample code snippet or a small example that demonstrates use http or socks proxy to create a client and operate google sheets through sheets api? It would be incredibly helpful for me to understand how to approach this problem.

Thank you so much for your time and assistance. I really appreciate any help you can provide.

**Comment by HustCoderHu** [comment]
refer to example/main.go,  u won't miss it  : )
