### ISSUE TITLE
Request for Go Client Library for Google Travel Partner API

### ISSUE THREAD

**Issue by tangvis** [googleapis/google-api-go-client#2859]
- What you're trying to do
I'm look for a GO library for Google Travel Partner API and I found a discovery document in its [API reference page](https://developers.google.com/hotels/hotel-prices/api-reference/rest), however, when I try to get the auto-gegerated client in this repo I just can't get one, so I try to figure out why, at last I found the reason is Travel Partner API is not in [the list](https://www.googleapis.com/discovery/v1/apis). I have searched a lot but didn't get the reason why it was excluded.
Could you please add it into the list so that we can get the client? We are in dire need of it.
- What code you've already tried
I have attampted to generate the client in my own repo, but I believe it will be greatly beneficial to have an official client in this repo.
- Any error messages you're getting
no

Thank you.

**Comment by quartzmo** [comment]
The client libraries in this repo are based on interface descriptions published by product teams. We are only able to assist with issues that pertain to the behavior of the libraries themselves. Because the decision to publish a `travelpartner.googleapis.com` client belongs to the product team itself, please visit the [Support page](https://cloud.google.com/support) to reach the relevant engineers, or try [Hotel Center Help](https://support.google.com/hotelprices#topic=9301472) directly. Thanks!
