### ISSUE TITLE
androidpublisherv3: Cant create subscription. googleapi: Error 500: Internal error encountered., backendError

### ISSUE THREAD

**Issue by DulatKuntu** [googleapis/google-api-go-client#2929]
I have a code to programmatically create subscription in google play console. However, I get error **googleapi: Error 500: Internal error encountered., backendError**

```
monetization := androidpublisher.NewMonetizationService(service)

subscription := &androidpublisher.Subscription{
	PackageName: packageName,
	ProductId:   "1",
	BasePlans: []*androidpublisher.BasePlan{
		{
			BasePlanId: "one-dol-plan",
		},
	},
	Listings: []*androidpublisher.SubscriptionListing{
		{
			LanguageCode: "en-US",
			Title:        "Monthly Subscription 2",
			Description:  "Subscribe for premium access on a monthly basis",
		},
	},
	TaxAndComplianceSettings: &androidpublisher.SubscriptionTaxAndComplianceSettings{
		IsTokenizedDigitalAsset: true,
	},
}

// Create subscription via API
_, err = monetization.Subscriptions.Create(packageName, subscription).ProductId("1").RegionsVersionVersion("2022/02").Context(ctx).Do()
if err != nil {
	fmt.Println("Error creating subscription:", err)
}
```

According to the status code the error is on google's side. Please, help me with this issue

**Comment by quartzmo** [comment]
The client libraries in this repo are based on interface descriptions published by product teams. We are only able to assist with issues that pertain to the behavior of the libraries themselves. Because the issue you're experiencing is due to the design and/or behavior of the product and/or its API, please visit the [support page](https://cloud.google.com/support) to reach product engineers. To see if this problem has already been reported, you can check the Cloud issue trackers at https://cloud.google.com/support/docs/issue-trackers.
