### ISSUE TITLE
Missed list method for mediaItems in photoslibrary.

### ISSUE THREAD

**Issue by AyumuKasuga** [googleapis/google-api-go-client#309]
Hello! I noticed that method [list](https://developers.google.com/photos/library/reference/rest/v1/mediaItems/list) does not present [here](https://github.com/googleapis/google-api-go-client/blob/master/photoslibrary/v1/photoslibrary-api.json#L274-L344) hence it does not exist in generated go code...

**Comment by jadekler** [comment]
@AyumuKasuga Thanks for filing this issue! Unfortunately that library is no longer maintained. I believe the photos team does build their own libraries (not in Go, unfortunately): https://github.com/google?utf8=%E2%9C%93&q=photoslibrary&type=&language=.

I've raised this to them for visibility.

I've also created https://github.com/googleapis/google-api-go-client/issues/310 so that this kind of thing is communicated to users up front.
