### ISSUE TITLE
git.apache.org/thrift.git has gone away

### ISSUE THREAD

**Issue by y0ssar1an** [googleapis/google-api-go-client#347]
This line from `go.sum` is causing problems.
```
git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999/go.mod h1:fPE2ZNJGynbRyZ4dJvy6G277gSllfV2HJqblrnkyeyg=
```
https://github.com/jenkins-x/jx/blob/master/go.sum#L14

This git repo has been moved to https://github.com/apache/thrift . The old `git.apache.org/thrift.git` repo has been shut down. This might cause breakages for you when you try to make dependency changes.

**Comment by jadekler** [comment]
This is depended upon by opencensus, not us. They have since fixed the dependency https://github.com/census-instrumentation/opencensus-go/blob/master/go.mod#L4 but not yet put out a new version. Once they do we'll update our dependencies - tracking that in https://github.com/googleapis/google-api-go-client/issues/342.

cc @rghetia.

**Comment by rghetia** [comment]
go.opencensus.io [0.19.2](https://github.com/census-instrumentation/opencensus-go/releases/tag/v0.19.2) is released.

**Comment by cbalano** [comment]
FYI, I got past the issue by adding this line in go.mod, right above the require section:
<pre>
replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0
</pre>
