### ISSUE TITLE
compute: provide easier way to add container optimized OS options for deploying GCE instances

### ISSUE THREAD

**Issue by martinomburajr** [googleapis/google-api-go-client#361]
As of now, the API as well as the REST API option does not give the option to create a VM that accepts a parameter that refers to a Docker image on gcr.io. Effectively Container OS is not an option available through the APIs.

**Comment by bradfitz** [comment]
Yeah, I've had to do this by hand in the past.

* https://github.com/golang/build/blob/6994fc2d58f1bbe10751c98eddf52912ccc185ee/buildlet/gce.go#L146
* https://github.com/golang/build/blob/6994fc2d58f1bbe10751c98eddf52912ccc185ee/buildlet/gce.go#L458

**Comment by daddyfatstaks** [comment]
So what you're saying is I need to build a container OS? And fix some
missing pieces to the puzzle still? I feel a bit um how do I say it.....
Hmm not very smart compared to all you MIT and other coding wizards but
I've been watching and waiting for someone to show me the way and I thank
whoever finally did because it's been 4 years now on this wild goose chase.
Anyways sorry for clogging the workspace with simple chatter but I...
I..... 😉😁😁😁✌️🤘🤙👋🤟👏🙏👣

**Comment by daddyfatstaks** [comment]
Sweet 👍 oh man I'm going to pass out... The room is spinning

**Comment by jadekler** [comment]
Closing, since the issue seems resolved (thanks @bradfitz!). If there's more to discuss here, happy to re-open!

**Comment by bradfitz** [comment]
@jadekler, my point was that it's a PITA today. I understand the OP's request for it to be easier.

**Comment by jadekler** [comment]
Ah, right on. I'll update the title and turn it into a feature request.

**Comment by martinomburajr** [comment]
This is a better way to phrase it given the comments in this thread. Thanks @bradfitz  and @jadekler

**Comment by codyoss** [comment]
I am not sure if this is still an issue. If it is I would suggest reaching out with one of the options on the [Compute API support page](https://cloud.google.com/compute/docs/support). This seems like a feature request for the backend and not this auto-generated client.
