### ISSUE TITLE
bundler: implement more advanced queueing

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-api-go-client#367]
Currently, the bundler has a subtle queueing behavior that happens as such:

- Define [HandlerLimit](https://github.com/googleapis/google-api-go-client/blob/5213b809086156e6e2b262a41394993fcff97439/support/bundler/bundler.go#L77) to 1. Similarly, define [BundleCountThreshold](https://github.com/googleapis/google-api-go-client/blob/5213b809086156e6e2b262a41394993fcff97439/support/bundler/bundler.go#L61) to 1.
- Add several messages, but block on handling.
- The first message is sent to the handler in a goroutine (see [here](https://github.com/googleapis/google-api-go-client/blob/5213b809086156e6e2b262a41394993fcff97439/support/bundler/bundler.go#L266)).
- All other messages now wait in their own goroutines on sem.acquire (see [here](https://github.com/googleapis/google-api-go-client/blob/5213b809086156e6e2b262a41394993fcff97439/support/bundler/bundler.go#L271)).

So, the effect is that the semaphore acts as a queue where each queue item is a bundle to be processed and the goroutine it's waiting in.

There are several optimizations we could make here:

- ~Auto-timer:  if there is a non-empty queue when the currently-processing item is finished, immediately re-flush instead of waiting for the next DelayThreshold tick or Add call.~ Investigate: not an issue.
- Coalesce: if there is a non-empty queue when the next "flush" tick happens, try to coalesce several of those items before sending. Queues of less-than-maximum-size bundles can occur by way of [DelayThreshold](https://github.com/googleapis/google-api-go-client/blob/5213b809086156e6e2b262a41394993fcff97439/support/bundler/bundler.go#L55) (a low DelayThreshold will cause bundles that aren't full to be sent).

It's not clear whether either of these can be generalized beyond the HandlerLimit=1 case. Probably they can but it will be harder.

**Comment by jadekler** [comment]
cc @jba

**Comment by jadekler** [comment]
cc @escholtz

**Comment by jba** [comment]
> * Auto-timer:  if there is a non-empty queue when the currently-processing item is finished, immediately re-flush instead of waiting for the next DelayThreshold tick or Add call.

IIRC this is already what happens: the call to `release` [broadcasts](https://github.com/googleapis/google-api-go-client/blob/5213b809086156e6e2b262a41394993fcff97439/support/bundler/bundler.go#L307), which should immediately wake up the waiting goroutines.

**Comment by jadekler** [comment]
Yes, I agree.

**Comment by danscales** [comment]
I did a slight optimization with https://code-review.googlesource.com/c/google-api-go-client/+/47790

@escholtz is investigating more extensive optimizations, including the second one mentioned above ("Coalesce") and also a rewrite that would create a more explicit queue of ready Bundles, so that a goroutine that handles a bundle is not actually created until it can run right away (i.e. is handling the next bundle that will fit within HandleLimit).  Currently, in certain situations, a large number of goroutines can be created to send bundles, but are not runnable yet because of the low HandlerLimit, and so are being woken up repeatedly by the Broadcasts in acquire() and release().
