### ISSUE TITLE
Compute: Metadata filters don't work like gcloud CLI

### ISSUE THREAD

**Issue by ViBiOh** [googleapis/google-api-go-client#406]
Hi,

I'm using Golang client for retrieving compute instance with given filter, it works like a charm with gcloud CLI but does't with Go client.

```bash
gcloud compute instances list --filter 'metadata.lifecycle != day AND metadata.lifecycle != on-demand AND name !~ gke'
```

The same request in client

```go
lifecycleFilter := "metadata.lifecycle=day AND metadata.lifecycle!=on-demand AND name!~gke"
a.computeService.Instances.List(env.ID, zone).Filter(lifecycleFilter).MaxResults(maxResultsFromAPI).Do()
```

and getting error 

```
googleapi: Error 400: Invalid value for field 'filter': 'metadata.lifecycle=day AND metadata.lifecycle!=on-demand AND name!~gke'. Invalid list filter expression., invalid
```

I'm using `google.golang.org/api v0.10.0` (from my go.mod)

Is there a config that I should pass or change filter syntax ?

**Comment by jadekler** [comment]
Hello! This issue tracker is for the Go-specific generator and the output of that generator: unfortunately, the compute team doesn't frequent this tracker. Would you mind re-filing this issue on the compute team's issue tracker? They can be found under "Compute" on https://cloud.google.com/support/docs/issue-trackers.

**Comment by shibumi** [comment]
Just to complete this issue and help people who search for it via Google:

gcloud does client and server-side filtering. The syntax in this issue is client-side filter syntax and not supported by the Server API.

The server API follows https://google.aip.dev/160 and looks differently.

Additionally, there seems to be a bug in the server API: https://issuetracker.google.com/120255780
