### ISSUE TITLE
Stackdriver APIs have been broken by the latest commit

### ISSUE THREAD

**Issue by manugarg** [googleapis/google-api-go-client#425]
Commit 8a410c2 has broken Go packages dependent on the monitoring API.

For example, these are the errors from the [cloudprober build](https://travis-ci.org/google/cloudprober/jobs/612687951?utm_medium=notification&utm_source=email):
```
surfacers/stackdriver/stackdriver.go:136:16: cannot assign *monitoring.APIService to s.client (type *monitoring.Service) in multiple assignment
surfacers/stackdriver/stackdriver.go:211:26: s.client.Projects undefined (type *monitoring.Service has no field or method Projects)
```

After this commit, monitoring.New() returns monitoring.APIService instead of monitoring.Service.

func New(client *http.Client) (*Service, error) {
func New(client *http.Client) (*APIService, error) {
It must be an easy fix for cloudprober, but it seems this change has potential of breaking many packages.

CC: @shollyman

**Comment by jadekler** [comment]
This appears to be because the monitoring service now has a [Service](https://godoc.org/google.golang.org/api/monitoring/v3#Service) type, which means that NewService() has to return something else (which it now calls an APIService).

I realize this is quite confusing - unfortunately it's a side affect of this library being auto-generated. That is: the API producers had no way of knowing that the term "Service" was already being used by the library generator.

I don't know that there's a great solution to this conundrum: either we create a different, artisanal Go name for [Service](https://godoc.org/google.golang.org/api/monitoring/v3#Service) such as ServiceService and have NewService revert to returning a Service (this will also make the g3 import a lot easier...), or we leave as-is and break people. (which is "allowed" vis-a-vis https://godoc.org/google.golang.org/api#hdr-Versioning_and_Stability but best avoided where possible)

@broady @bradfitz do either of you have thoughts?

**Comment by jadekler** [comment]
Looks like over in the oneplatform side of things they do have a `service_servce.proto` and a [`ServiceMonitoringServiceServer`](https://github.com/googleapis/go-genproto/blob/master/googleapis/monitoring/v3/service_service.pb.go#L936). So, that makes the ServiceService type option a bit more palpable.

**Comment by broady** [comment]
Yeah unfortunately the APIService generation breaks packages if the Service
type was added later on.

Breaking is particularly bad if the package is a transitive dependency. I
would guess maybe OpenCensus holds a dep to this package? If there are no
significant library deps, then I'd probably lean towards breakage.

**Comment by jadekler** [comment]
Fix at https://code-review.googlesource.com/c/google-api-go-client/+/48591.
