### ISSUE TITLE
Provide interfaces

### ISSUE THREAD

**Issue by kwiesmueller** [googleapis/google-api-go-client#480]
Would it be possible, to provide interfaces for the generated types here?
It's really hard to test and build mocks/fakes for the types defined by the various packages.
With proper interface definitions, one could generate mocks and fakes to use in tests.

**Comment by codyoss** [comment]
Hey,

It is a design decision of this api to not expose interfaces for our service. The reason is if we make an interface we can't add a method to it in a backwards compatible way. For more information see: https://github.com/golang/go/wiki/CodeReviewComments#interfaces

Some options:
- Define your own interfaces and use those in your code.
- Make use of `option.WithHTTPClient` to make a fake backend

**Comment by kwiesmueller** [comment]
Sounds reasonable, thanks.
