### ISSUE TITLE
all: move presubmits off kokoro and use GitHub Actions instead

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-api-go-client#504]
Kokoro can be really slow at times, GitHub actions seem fast. Should we migrate our presubmit to actions?

**Comment by codyoss** [comment]
cc @broady @tbpg Thoughts?

**Comment by tbpg** [comment]
cc @JustinBeckwith 

Seems reasonable to me. But, we might need broader coordination.

**Comment by broady** [comment]
Think we should figure out why Kokoro is slowing us down. What about it is slow (can you link to build logs?) and what about GitHub actions seems fast?

We've invested a lot in it and we need more data to support a move to Actions in the long-run.

**Comment by broady** [comment]
Could it be because this repo takes forever for a checkout?

**Comment by JustinBeckwith** [comment]
I think the reasons here are important.  For Node.js and Java, we were fighting GitHub personal access token quota due to the split repositories.  We were frequently in a state where the key was getting maxed out, and it blocked Kokoro CI for the whole org.  

For node at least, system tests and sample tests still run on Kokoro.  And, they're the long pole in terms of time spent.  

I am supportive of us doing more with Actions, I just want to do it intentionally 🙃

**Comment by codyoss** [comment]
Closing as there seems to be no reason to move right now.
