### ISSUE TITLE
idtoken: support authorized_user credentials

### ISSUE THREAD

**Issue by bakins** [googleapis/google-api-go-client#577]
I run several services in Cloud Run using https://cloud.google.com/run/docs/authenticating/overview as well as services on GKE behind IAP.

I also have command line utilities for testing, querying, etc to talk to these services.  When possible, I'd rather use personal credentials rather than walking other developers through creating service accounts with keys, etc.   Also using personal credentials means I can use existing gsuite groups to designate who has access as well.

**Comment by codyoss** [comment]
Hey sorry for the slow response here. I would like to propose a different solution that might work here. If you had a service account and granted uses the Token creator role you could use the iamcredentials API to generate yourself an ID token.

I took a quick look at your PR and it does not actually generate you a token with the correct audience. You can run it through the `Validate` function and see what the parsed token looks like. A JWT is needed so you can set custom claims like the audience. In order to sign the JWT you need the private key, which is why a service account is used and not a user credential.

Hope that helps clear some things up, let me know if you have any questions.

**Comment by bakins** [comment]
@codyoss Thanks for the feedback.  I can look at the iamcredentials API. Any quick links to examples?  Also, FWIW, idtokens work fine with fully managed cloud run authenticated services (which is what we generally use) https://cloud.google.com/run/docs/authenticating/developers 🤷

**Comment by codyoss** [comment]
I am not sure we have samples for that api, but here is something I wrote quick:

```go
import (
	"context"
	"fmt"
	"log"
	"os"

	"google.golang.org/api/iamcredentials/v1"
)

func main() {
	ctx := context.Background()
	svc, err := iamcredentials.NewService(ctx)
	if err != nil {
		log.Fatalf("creating client: %v", err)
	}

	name := fmt.Sprintf("projects/-/serviceAccounts/%s", os.Getenv("SA_NAME"))
	resp, err := svc.Projects.ServiceAccounts.GenerateIdToken(name, &iamcredentials.GenerateIdTokenRequest{
		Audience: os.Getenv("RUN_URL"),
	}).Do()
	if err != nil {
		log.Fatalf("executing request: %v", err)
	}
	log.Printf("This is the ID token: %v", resp.Token)
}

```
