### ISSUE TITLE
ForceSendFields creates security issues

### ISSUE THREAD

**Issue by dustin-decker** [googleapis/google-api-go-client#610]
This lib has a field called `ForceSendFields` to allow you to specify sending particular fields when they are set to their 'default' value. 

The bool default value is `false`, and typically causes the most issues.

Take CloudSQL instances, for example. `Ipv4Enabled` controls whether the instance is created with a public IP. The field defaults to true (but not the value). So if you specify `false` because you only want a private IP, that is not enough, because your value will never be sent to the API. You must also specify `ForceSendFields:    []string{"Ipv4Enabled"},` for it to be sent.
Example: https://github.com/terraform-providers/terraform-provider-google/blob/903d80df70330f1895208191156ebcfc000af2c3/google/resource_sql_database_instance.go#L795

This has caused myself and others time and frustration, and no doubt has caused unintended public exposure of many CloudSQL instances among other issues in other APIs.

Could all specified values be sent by default? There are two ways that I see to accomplish this without changing the defaults:
1) Nillable values and only sending non-nil pointers.
2) Specify the defaults in the client. Use an initialization function with functional options rather than having users use the raw structs.

**Comment by codyoss** [comment]
It was a design decision of these clients to to work with builtin types rather than making everything a pointer to make the experience more idiomatic . Because of this, in conjunction with the fact we use `omitemtpy` on all fields, we needed a way to send default values: `ForceSendFields`. In the case of a bool this gives us three options: true, false(with ForceSendFields), false(with ForceSendFields -- not sent). This is documented on every struct. 

> Could all specified values be sent by default?

Not without have a large breaking change release.
