### ISSUE TITLE
image: image.Deprecated is deprecated: The deprecation status associated with this image

### ISSUE THREAD

**Issue by bh7cw** [googleapis/google-api-go-client#767]
golang-ci lint shows the error:
```
image.Deprecated is deprecated: The deprecation status associated with this image.  (staticcheck)
```
According to:
```
type Image struct {
	// ArchiveSizeBytes: Size of the image tar.gz archive stored in Google
	// Cloud Storage (in bytes).
	ArchiveSizeBytes int64 `json:"archiveSizeBytes,omitempty,string"`

	// CreationTimestamp: [Output Only] Creation timestamp in RFC3339 text
	// format.
	CreationTimestamp string `json:"creationTimestamp,omitempty"`

	// Deprecated: The deprecation status associated with this image.
	Deprecated *DeprecationStatus `json:"deprecated,omitempty"`
```
Deprecated was supported, but it's deprecated now.

According to [doc](https://cloud.google.com/compute/docs/reference/rest/v1/images/deprecate), `deprecated` is still supported.

How to check the deprecated status of image through api?

**Comment by codyoss** [comment]
Hey, thanks for the report. This field is not actually deprecated. `staticcheck` just reports it as such because the godoc starts with `Deprecated:`. It looks like our generator writes docs as `(fieldname): (description)` and the field name here happens to be `Deprecated `. The offending code lies here: https://github.com/googleapis/google-api-go-client/blob/master/google-api-go-generator/gen.go#L1359.

**Comment by bh7cw** [comment]
Hah, okay. Thank you for quick reply and clarification.
