### ISSUE TITLE
Compute: How to filter instances based on networkInterfaces

### ISSUE THREAD

**Issue by rodrigopavan** [googleapis/google-api-go-client#813]
How can I/It's possible filter instances base on **network** attribute inside networkInterfaces?

I've tried a few things like:
`req := c.ComputeService.Instances.List(projectID, zoneName).Filter('networkInterfaces[0].network=" + networkSelfLink + "')`

`req := c.ComputeService.Instances.List(projectID, zoneName).Filter('networkInterfaces.network=" + networkSelfLink + "')`

But, none of them works, I always receive an:
`Invalid value for field 'filter': 'networkInterfaces[0].network="https://www.googleapis.com/compute/v1/projects/simreplicacao/global/networks/default"'. Invalid list filter expression.`

**Comment by codyoss** [comment]
By looking at the [docs](https://cloud.google.com/compute/docs/reference/rest/v1/instances/list) it appears `items[].networkInterfaces[].network` might be what you are looking for.

**Comment by rodrigopavan** [comment]
@codyoss , doens't works...

{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'filter': 'networkInterfaces[].network=\"https://www.googleapis.com/compute/v1/projects/ns1-ddi-integration-proj-01/global/networks/default\"'. Invalid list filter expression.",
    "errors": [
      {
        "message": "Invalid value for field 'filter': 'networkInterfaces[].network=\"https://www.googleapis.com/compute/v1/projects/ns1-ddi-integration-proj-01/global/networks/default\"'. Invalid list filter expression.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}`


`{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'filter': 'items[].networkInterfaces[].network=\"https://www.googleapis.com/compute/v1/projects/ns1-ddi-integration-proj-01/global/networks/default\"'. Invalid list filter expression.",
    "errors": [
      {
        "message": "Invalid value for field 'filter': 'items[].networkInterfaces[].network=\"https://www.googleapis.com/compute/v1/projects/ns1-ddi-integration-proj-01/global/networks/default\"'. Invalid list filter expression.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
`

**Comment by codyoss** [comment]
Sorry for the misdirection. If this field could be filtered on you could do it with a `:`, see [AIP-160](https://google.aip.dev/160) for example syntax. I did also find an open issue related to unable to filter on networkinterfaces though as well: [issue](https://b.corp.google.com/issues/73455339). If this is the case the issue is not with this client, but the backend service. I would recommend reaching out for support through one of the methods listed on the compute api [support page](https://cloud.google.com/compute/docs/support).

This issue tracker is primarily used for issue relating the the generated code itself.
