### ISSUE TITLE
cloudidentity/v1 missing OperationService

### ISSUE THREAD

**Issue by estenssoros** [googleapis/google-api-go-client#941]
I noticed that methods in the cloudidentity/v1.Service return an *Operation similar to the cloudresourcemanager/v2.  In cloudresourcemamanger we are able to poll the status of the operation via the OperationService and eventually unmarshal the result. It seems this Service is missing for the cloudidentity/v1. Is this by design? If so, how are we supposed to check the status of the API call?

cloudresourcemanager
- `Folder.Create("folder").Do() (*Operation, error) {...}`
- `Operations.Get(opName).Do() (*Operation, error) {...}`

cloudidentity
- `Groups.Create("group").Do() (*Operation, error) {...}`
- ...

I am using google.golang.org/api v0.42.0

Thank you,

**Comment by codyoss** [comment]
Hey, thank you for filing the issue. I agree something does not seem quite right here. Services that expose these long running operations should provide apis for working with those operations. These apis are generally found at "${basePath}/${apiVersion}/operations/${opID}". It seems like this service is not exposing those endpoints. As this seems to be an issue with the service can I ask you to please file a bug with that service. You can find a link to their issue tracker [here](https://cloud.google.com/identity/docs/resources/support). Please feel free to post back a link to that issue here so others can follow too. Thanks!
