### ISSUE TITLE
Unarchiving a user is ineffective unless Archived is sent in ForceSendFields

### ISSUE THREAD

**Issue by cwalkatron** [googleapis/google-api-go-client#986]
The following code does nothing.

```go
_, err := dirSrv.Users.Update(userKey, &admin.User{Archived: false}).Do()
```

However, adding `Archived` to `ForceSendFields` makes it work. This is not obvious.

```go
_, err := dirSrv.Users.Update(userKey, &admin.User{
                  Archived:        false,
                  ForceSendFields: []string{"Archived"}}).Do()
```

**Comment by codyoss** [comment]
Hey, sorry you had trouble with this. For boolean fields like this the `ForceSendFields` field is required because the struct is labeled as with the json tag `omitempty`, cause default values not to be serialized. Besides the docs found on the struct we also include an explanation in our package docs: [ForceSendFields](https://pkg.go.dev/google.golang.org/api#hdr-ForceSendFields). If you have suggestions about where else we could put some documentation please let us know!
